apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lab2-chart.fullname" . }}-config
data:
  MDB_URL: {{printf "%s" (include "mongodb.clientstring" .) | quote}}
  MDB_WORKDB: "otus"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lab2-chart.fullname" . }}-secret
type: Opaque
data:
  MDB_USER: {{.Values.secret.mdbuser | b64enc | quote}}
  MDB_PASSWORD: {{.Values.secret.mdbpassword | b64enc |  quote}}
  MDB_ROOTPASSWORD: {{.Values.mongodb.auth.rootPassword | b64enc | quote}}

