apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lab2-chart.fullname" . }}
  labels:
    {{- include "lab2-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "lab2-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lab2-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          env:
            - name: MDB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lab2-chart.fullname" . }}-config
                  key: MDB_URL
            - name: MDB_WORKDB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lab2-chart.fullname" . }}-config
                  key: MDB_WORKDB
            - name: MDB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "lab2-chart.fullname" . }}-secret
                  key: MDB_USER
            - name: MDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "lab2-chart.fullname" . }}-secret
                  key: MDB_PASSWORD
