{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lab2-chart.fullname" . }}
  labels:
    {{- include "lab2-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "lab2-chart.fullname" . }}
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "lab2-chart.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
{{- end }}      
