# Default values for lab2-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

autoscaling:
  enabled: false
image:
  repository: alcaver/otuswork
  pullPolicy: IfNotPresent



service:
  type: NodePort
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  tls: false
  annotations: { nginx.ingress.kubernetes.io/rewrite-target: /$1}
  
  hosts:
    - host: docker.tk-chel.ru
      paths: ['/(.*)']

    - host: arch.homework
      paths: ['/otusapp/alcaver/(.*)']

secret:
  mdbuser: YWxleA==
  mdbpassword: cGFzc3dvUmQ=
metrics:
  serviceMonitor:
    enabled: true


mongodb:
  architecture: replicaset
  replicaCount: 3
  auth:
    enabled: true
    rootPassword: passwoRd

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
